################################### Required ######################################
# globals params for all microservices like (eureka, database ...)

#/applis/28005-free0
app_dir: /opt/microservices
#/applis/logs/28005-free0
app_dir_log: /opt/microservices/logs
#/applis/data/28005-free0
app_dir_data: /opt/microservices/data
#/applis/delivery/28005-free0
app_dir_delivery: /opt/microservices/delivery