---
all:
  children:
    MN:
      children:
        front:
          children:
            ihs:
              hosts:
                s01vl9995163.fr.net.intra:
            microservice:
              hosts:
                s01vl9995163.fr.net.intra:
        back:
          children:
            microservice:
              hosts:
                s01vl9995246.fr.net.intra:
            cft:
              hosts:
                s01vl9995267.fr.net.intra:
            mq:
              hosts:
                s01vl9995268.fr.net.intra:
            mongo:
              children:
                live:
                  hosts:
                    s01vl9995277.fr.net.intra:
                    s01vl9995279.fr.net.intra:
                archive:
                  hosts:
                    s01vl9995282.fr.net.intra:
                    s01vl9995284.fr.net.intra:
                    s01vl9995285.fr.net.intra:

    ME:
      children:
        front:
          children:
            ihs:
              hosts:
                s01vl9995264.fr.net.intra:
            microservice:
              hosts:
                s01vl9995264.fr.net.intra:
        back:
          children:
            microservice:
              hosts:
                s01vl9995266.fr.net.intra:
            cft:
              hosts:
            mq:
              hosts:
                s01vl9995269.fr.net.intra:
            mongo:
              children:
                live:
                  hosts:
                    s01vl9995278.fr.net.intra:
                archive:
                  hosts:
                    s01vl9995286.fr.net.intra:
                    s01vl9995287.fr.net.intra:
                    s01vl9995288.fr.net.intra:
