---
all:
  children:
    MN:
      children:
        front:
          children:
            ihs:
              hosts:
                s01vl9995247.fr.net.intra:
            microservice:
              hosts:
                s01vl9995247.fr.net.intra:
        back:
          children:
            microservice:
              hosts:
                s01vl9995271.fr.net.intra:
            mq:
              hosts:
                s01vl9995273.fr.net.intra:


    ME:
      children:
        front:
          children:
            ihs:
              hosts:
                s01vl9995270.fr.net.intra:
            microservice:
              hosts:
                s01vl9995270.fr.net.intra:
        back:
          children:
            microservice:
              hosts:
                s01vl9995272.fr.net.intra:
