service-registration-and-discovery-client:
  app_name: service-registration-and-discovery-client
  ms_type: front
  ms_number: 2
  app_vesrion: 0.0.1-SNAPSHOT
  log_sub_dir: /log
  data_sub_dir: /data
  pid_sub_dir: /pid
  tmp_sub_dir: /tmp
  dmp_sub_dir: /dmp
  config_sub_dir: /config
  properties_file_name: application.properties
  springboot_backend_name: back

service-registration-and-discovery-service:
  app_name: service-registration-and-discovery-service
  ms_type: back
  ms_number: 1
  app_vesrion: 0.0.1-SNAPSHOT
  log_sub_dir: /log
  data_sub_dir: /data
  pid_sub_dir: /pid
  tmp_sub_dir: /tmp
  dmp_sub_dir: /dmp
  config_sub_dir: /config
  properties_file_name: application.properties
